# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('number', models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_purchases', to='shop.Product')),
            ],
            options={
                'ordering': ('-product_count',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('number', models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accepted', models.BooleanField(default=False)),
                ('product_in', models.ManyToManyField(related_name='in_transaction', through='shop.Purchase', to='shop.Product')),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bot.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_in', to='shop.Transaction'),
        ),
    ]
