# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.UUIDField(default=uuid.UUID('505b4d02-4c42-49c6-b915-3a0db93b9880'), editable=False, unique=True),
        ),
    ]
