# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_transaction_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('count',)},
        ),
    ]
