# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180410_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='count',
        ),
    ]
